### ISSUE TITLE
The result asks for advice

### ISSUE THREAD

**Issue by callaL** [ylab-hi/ScanITD#1]
Thank you for developing this useful tool. I have some doubts about the running results. The starting and ending points of the results in the following screenshot are the same. I noticed that the AO of these lines is different. Could you please explain to me why such results appear? How to choose between these lines
Looking forward to your reply soon!
![image](https://user-images.githubusercontent.com/52152132/94656941-56d5ce00-0333-11eb-855b-08ab96abfffd.png)
![1](https://user-images.githubusercontent.com/52152132/94657153-9a303c80-0333-11eb-9937-af2379428b4d.png)

**Comment by dolittle007** [comment]
Thank you for using this tool.
Due to the nature of ITD, the informative reads (softclipped/Insertion) could locate in any position within one ITD, see the supplementary figure 1. ScanITD may report the same event multiple times since we utilized this information to infer ITD. You may use the highest AO/AB or averaged one to report this ITD event.   
Hope it will help you.
